- name: git
  hosts: all
  gather_facts: False
  tasks:
    - name: set is_amazon_ebs
      set_fact:
        is_amazon_ebs: "{{ build_type == 'amazon-ebs' }}"
    - name: install packages
      become: "{{ is_amazon_ebs }}"
      yum: name={{ item }} state=present
      with_items:
        - gcc
        - autoconf
        - openssl-devel
        - curl-devel
        - expat-devel
        - perl-ExtUtils-MakeMaker
        - gettext
    - name: clean yum cache
      become: "{{ is_amazon_ebs }}"
      command: yum clean all
    - name: unarchive git tarball
      unarchive:
        src: https://github.com/git/git/archive/v{{ version }}.tar.gz
        dest: .
        remote_src: True
    - name: install git
      command: " {{ item }} chdir=git-{{ version }} "
      with_items:
        - autoconf
        - ./configure --prefix=/tmp/usr --with-curl
        - make install
    - name: archive installed git dir
      command: tar czf dest.tar.gz -C /tmp usr
    - name: clean up git source dir
      file:
        path: git-{{ version }}
        state: absent
